import numpy as np

SPEED_OF_SOUND = 343
SAMPLE_RATE = 48000
CHUNK_SIZE = 10000

CORRELATION_WINDOW = 15
CORRELATION_RANGE = 2 * CORRELATION_WINDOW + 1

MIC_ARRAY_RADIUS = 0.045
NUM_CIRCULAR_MICS = 6
MIC_ANGLES = np.linspace(0, 2 * np.pi, NUM_CIRCULAR_MICS, endpoint=False)

SMOOTHING_WINDOW_LEN = 50
SMOOTHING_ALPHA = 0.2

SHOW_PROBABILITY = False

NUM_STEPS_PHI_ANGLE = 6400
