import numpy as np
from pyaudio import paInt16

SAMPLE_FORMAT = paInt16

SPEED_OF_SOUND = 343
SAMPLE_RATE = 48000
CHUNK_SIZE = 10000

CORRELATION_WINDOW = 15
CORRELATION_RANGE = 2 * CORRELATION_WINDOW + 1

MIC_ARRAY_RADIUS = 0.04
NUM_CIRCULAR_MICS = 6
MIC_ANGLES = np.linspace(0, 2 * np.pi, NUM_CIRCULAR_MICS, endpoint=False)

FILTER_CENTER_FREQ = 2500
FILTER_BANDWIDTH = 3000
FILTER_LOW_CUTOFF = FILTER_CENTER_FREQ - FILTER_BANDWIDTH / 2
FILTER_HIGH_CUTOFF = FILTER_CENTER_FREQ + FILTER_BANDWIDTH / 2
FILTER_NUMTAPS = 1010

SMOOTHING_WINDOW_LEN = 50
SMOOTHING_ALPHA = 0.2

SHOW_PROBABILITY = False

AUDIO_CHUNK_DURATION = CHUNK_SIZE / SAMPLE_RATE

NUM_STEPS_PHI_ANGLE = 6400

mics = np.array([[0, 0]])
for angle in MIC_ANGLES:
    mics = np.vstack([mics, [MIC_ARRAY_RADIUS * np.cos(angle), MIC_ARRAY_RADIUS * np.sin(angle)]])
